
CREATE TABLE IF NOT EXISTS shops(id TEXT PRIMARY KEY,name TEXT NOT NULL,hours TEXT NOT NULL DEFAULT '',contact TEXT NOT NULL DEFAULT '',details TEXT NOT NULL DEFAULT '',password_hash TEXT NOT NULL,salt TEXT NOT NULL,is_demo INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS shop_stock(shop_id TEXT NOT NULL,sku TEXT NOT NULL,name TEXT NOT NULL,qty INTEGER NOT NULL CHECK(qty>=0),price TEXT NOT NULL DEFAULT '',updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(shop_id,sku),FOREIGN KEY(shop_id) REFERENCES shops(id));
CREATE TABLE IF NOT EXISTS shop_pending(id TEXT PRIMARY KEY,shop_id TEXT NOT NULL,customer TEXT NOT NULL,sku TEXT NOT NULL,qty INTEGER NOT NULL CHECK(qty>0),pickup TEXT NOT NULL,created_at INTEGER NOT NULL,FOREIGN KEY(shop_id,sku) REFERENCES shop_stock(shop_id,sku));
CREATE TABLE IF NOT EXISTS shop_orders(id TEXT PRIMARY KEY,shop_id TEXT NOT NULL,customer TEXT NOT NULL,sku TEXT NOT NULL,qty INTEGER NOT NULL CHECK(qty>0),pickup TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'accepted',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(shop_id,sku) REFERENCES shop_stock(shop_id,sku));
CREATE TRIGGER IF NOT EXISTS shop_reserve BEFORE INSERT ON shop_orders BEGIN
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM shop_stock WHERE shop_id=NEW.shop_id AND sku=NEW.sku AND qty>=NEW.qty) THEN RAISE(ABORT,'insufficient_stock') END;
 UPDATE shop_stock SET qty=qty-NEW.qty,updated_at=CURRENT_TIMESTAMP WHERE shop_id=NEW.shop_id AND sku=NEW.sku;
END;
CREATE TABLE IF NOT EXISTS shop_sessions(id TEXT PRIMARY KEY,shop_id TEXT NOT NULL,created_at INTEGER NOT NULL,requests INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS auth_limits(key TEXT PRIMARY KEY,attempts INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS creator_auth(id INTEGER PRIMARY KEY CHECK(id=1),password_hash TEXT NOT NULL,salt TEXT NOT NULL);
