
PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS settings(id INTEGER PRIMARY KEY CHECK(id=1), name TEXT NOT NULL, hours TEXT NOT NULL DEFAULT '', contact TEXT NOT NULL DEFAULT '', details TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS stock(sku TEXT PRIMARY KEY,name TEXT NOT NULL,qty INTEGER NOT NULL CHECK(qty>=0),price TEXT NOT NULL DEFAULT '',updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS pending(id TEXT PRIMARY KEY,customer TEXT NOT NULL,sku TEXT NOT NULL,qty INTEGER NOT NULL CHECK(qty>0),pickup TEXT NOT NULL,created_at INTEGER NOT NULL, FOREIGN KEY(sku) REFERENCES stock(sku));
CREATE TABLE IF NOT EXISTS orders(id TEXT PRIMARY KEY,customer TEXT NOT NULL,sku TEXT NOT NULL,qty INTEGER NOT NULL CHECK(qty>0),pickup TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'accepted',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(sku) REFERENCES stock(sku));
CREATE TRIGGER IF NOT EXISTS reserve_stock BEFORE INSERT ON orders BEGIN
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM stock WHERE sku=NEW.sku AND qty>=NEW.qty) THEN RAISE(ABORT,'insufficient_stock') END;
 UPDATE stock SET qty=qty-NEW.qty,updated_at=CURRENT_TIMESTAMP WHERE sku=NEW.sku;
END;
CREATE TABLE IF NOT EXISTS events(id TEXT PRIMARY KEY,status TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
