import {profile,slot} from './service.mjs';

import {classify,stockReply} from './core.mjs';
export const j=(x,status=200)=>new Response(JSON.stringify(x),{status,headers:{'content-type':'application/json','cache-control':'no-store','x-content-type-options':'nosniff'}});
export async function body(r){const t=await r.text();if(t.length>30000)throw Error('Request too large');return JSON.parse(t)}
export async function hash(password,salt){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);const b=await crypto.subtle.deriveBits({name:'PBKDF2',salt:new TextEncoder().encode(salt),iterations:100000,hash:'SHA-256'},key,256);return Array.from(new Uint8Array(b),x=>x.toString(16).padStart(2,'0')).join('')}
const token=r=>(r.headers.get('authorization')||'').replace(/^Bearer /,'');
async function admin(r,e){const a=await e.DB.prepare('SELECT * FROM creator_auth WHERE id=1').first();return a?await hash(token(r),a.salt)===a.password_hash:!!e.ADMIN_TOKEN&&token(r)===e.ADMIN_TOKEN}
export async function allowed(r,e,id){const key=(r.headers.get('cf-connecting-ip')||'local')+':'+id+':'+Math.floor(Date.now()/900000);const l=await e.DB.prepare('SELECT attempts FROM auth_limits WHERE key=?').bind(key).first();if(l?.attempts>=30)return false;let ok;if(id==='creator')ok=await admin(r,e);else{const a=await e.DB.prepare('SELECT password_hash,salt FROM shops WHERE id=?').bind(id).first();ok=!!a&&await hash(token(r),a.salt)===a.password_hash;}if(!ok)await e.DB.prepare('INSERT INTO auth_limits(key,attempts) VALUES(?,1) ON CONFLICT(key) DO UPDATE SET attempts=attempts+1').bind(key).run();return ok}
export function details(b){if(typeof b.name!=='string'||!b.name.trim()||b.name.length>150)throw Error('Store name required');return [b.name.trim(),String(b.hours||'').slice(0,300),String(b.contact||'').slice(0,500),String(b.details||'').slice(0,6000)]}
function item(b){if(!/^[a-z0-9-]{1,40}$/.test(b.sku)||!b.name||!Number.isInteger(b.qty)||b.qty<0||b.qty>100000)throw Error('Invalid stock row');return [b.sku,String(b.name).slice(0,100),b.qty,String(b.price||'').slice(0,100)]}
async function chat(text,customer,id,db){const s=await db.prepare('SELECT name,hours,contact,details,is_demo FROM shops WHERE id=?').bind(id).first();if(!s)return 'Shop not found.';const c=classify(text);const all=async()=>(await db.prepare('SELECT sku,name,qty,price FROM shop_stock WHERE shop_id=? ORDER BY name LIMIT 200').bind(id).all()).results;
if(c.kind==='greeting')return `Hi! Welcome to ${s.name}. Ask stock, hours or owner contact. Use the pickup form to review and confirm a request. No payment is collected here.`;
if(c.kind==='contact')return s.contact||'Public owner contact not configured.';
if(c.kind==='hours')return s.hours||'Hours not configured.';
if(text.trim().toLowerCase()==='/stock')return (await all()).map(x=>`${x.sku}: ${x.name} - ${x.qty} available${x.price?' - '+x.price:''}`).join('\n')||'No stock added.';
if(c.kind==='stock'){const m=(await all()).filter(x=>c.text.includes(x.sku.toLowerCase())||c.text.includes(x.name.toLowerCase()));return stockReply(m.length===1?m[0]:null)}
if(c.kind==='order'){if(c.qty<1||c.qty>100||c.pickup.length>120)return 'Use quantity 1-100 and a short pickup time.';const x=await db.prepare('SELECT * FROM shop_stock WHERE shop_id=? AND sku=?').bind(id,c.sku).first();if(!x||x.qty<c.qty)return 'That item/quantity is unavailable. Check stock.';const oid=crypto.randomUUID();await db.prepare('INSERT INTO shop_pending VALUES(?,?,?,?,?,?,?)').bind(oid,id,customer,c.sku,c.qty,c.pickup,Date.now()).run();return `Review: ${c.qty} x ${x.name}, pickup ${c.pickup}; ${x.price||'price to confirm with owner'}. No payment or reservation yet. Confirm within 15 minutes: /confirm ${oid}. Contact owner for changes.`}
if(c.kind==='confirm'){const q=await db.prepare('SELECT * FROM shop_orders WHERE id=? AND shop_id=? AND customer=?').bind(c.id,id,customer).first();if(q)return 'Order '+c.id+' already saved. No duplicate.';const p=await db.prepare('SELECT * FROM shop_pending WHERE id=? AND shop_id=? AND customer=?').bind(c.id,id,customer).first();if(!p||Date.now()-p.created_at>900000)return 'Request expired or not found.';try{await db.batch([db.prepare('INSERT INTO shop_orders(id,shop_id,customer,sku,qty,pickup) SELECT id,shop_id,customer,sku,qty,pickup FROM shop_pending WHERE id=? AND shop_id=? AND customer=?').bind(c.id,id,customer),db.prepare('DELETE FROM shop_pending WHERE id=? AND shop_id=? AND customer=?').bind(c.id,id,customer)])}catch{return 'Could not reserve. Stock may have changed; check stock.'}return `Order saved: ${c.id}. ${p.qty} x ${p.sku}, pickup ${p.pickup}. Stock reserved. Owner sees this in their dashboard. No payment or push alert. Contact owner for changes.`}
return 'Ask stock, hours, or owner contact. '+s.details;
}
export async function multi(r,e){const u=new URL(r.url),p=u.pathname;if(p==='/creator'||p==='/creator.html')return e.ASSETS.fetch(new Request(u.origin+'/creator.html',r));if(/^\/(s|o)\/[a-f0-9-]{36}\/?$/.test(p)){const id=p.split('/')[2];if(!await e.DB.prepare('SELECT id FROM shops WHERE id=?').bind(id).first())return new Response('Shop not found',{status:404});const svc=await e.DB.prepare('SELECT shop_id FROM service_profiles WHERE shop_id=?').bind(id).first();return e.ASSETS.fetch(new Request(u.origin+(svc?(p.startsWith('/s/')?'/service':'/service-owner'):(p.startsWith('/s/')?'/shop':'/shop-owner')),r))}
if(!p.startsWith('/api/creator')&&!p.startsWith('/api/shops/'))return null;
try{if(r.method!=='GET'&&r.headers.get('origin')!==u.origin)return j({error:'Origin denied'},403);
if(p.startsWith('/api/creator')){if(!await allowed(r,e,'creator'))return j({error:'Wrong creator password or too many attempts'},401);
if(p==='/api/creator/password'&&r.method==='POST'){const b=await body(r);if(typeof b.password!=='string'||b.password.length<12||b.password.length>200)return j({error:'Use 12-200 characters'},400);const salt=crypto.randomUUID(),h=await hash(b.password,salt);await e.DB.prepare('INSERT INTO creator_auth VALUES(1,?,?) ON CONFLICT(id) DO UPDATE SET password_hash=excluded.password_hash,salt=excluded.salt').bind(h,salt).run();return j({saved:true})}
if(p==='/api/creator/shops'&&r.method==='GET'){const rows=(await e.DB.prepare("SELECT s.id,s.name,s.is_demo,s.created_at,COALESCE(p.business_type,'shop') business_type FROM shops s LEFT JOIN service_profiles p ON p.shop_id=s.id ORDER BY s.created_at DESC LIMIT 200").all()).results;return j({shops:rows.map(x=>({...x,customerUrl:u.origin+'/s/'+x.id,ownerUrl:u.origin+'/o/'+x.id}))})}
if(p==='/api/creator/shops'&&r.method==='POST'){const b=await body(r),d=details(b);if(typeof b.password!=='string'||b.password.length<12||b.password.length>200)return j({error:'Owner password must be 12-200 characters'},400);if(!Array.isArray(b.stock)||b.stock.length>100)return j({error:'Maximum 100 stock rows'},400);const serviceType=b.business_type&&b.business_type!=='shop';const rows=serviceType?[]:b.stock.map(item);if(new Set(rows.map(x=>x[0])).size!==rows.length)return j({error:'Duplicate item code'},400);const id=crypto.randomUUID(),salt=crypto.randomUUID(),h=await hash(b.password,salt);const extra=[];if(serviceType){const v=profile(b);extra.push(e.DB.prepare('INSERT INTO service_profiles(shop_id,business_type,working_days,address,services,fees,timezone) VALUES(?,?,?,?,?,?,?)').bind(id,...v));if(!Array.isArray(b.slots)||b.slots.length>100)throw Error('Invalid slots');for(const bslot of b.slots){const x=slot(bslot,{working_days:v[1]});extra.push(e.DB.prepare('INSERT INTO appointment_slots(id,shop_id,starts_at,ends_at,service) VALUES(?,?,?,?,?)').bind(x[0],id,...x.slice(1)))}}await e.DB.batch([e.DB.prepare('INSERT INTO shops(id,name,hours,contact,details,password_hash,salt,is_demo) VALUES(?,?,?,?,?,?,?,?)').bind(id,...d,h,salt,b.is_demo===false?0:1),...rows.map(x=>e.DB.prepare('INSERT INTO shop_stock(shop_id,sku,name,qty,price) VALUES(?,?,?,?,?)').bind(id,...x)),...extra]);return j({created:true,id,customerUrl:u.origin+'/s/'+id,ownerUrl:u.origin+'/o/'+id},201)}return j({error:'Not found'},404)}
const m=p.match(/^\/api\/shops\/([a-f0-9-]{36})\/(customer|chat|state|setup|stock)$/);if(!m)return j({error:'Not found'},404);const [,id,action]=m;const s=await e.DB.prepare('SELECT name,hours,contact,details,is_demo FROM shops WHERE id=?').bind(id).first();if(!s)return j({error:'Shop not found'},404);
if(action==='customer'&&r.method==='GET')return j({business:s,stock:(await e.DB.prepare('SELECT sku,name,qty,price FROM shop_stock WHERE shop_id=? ORDER BY name LIMIT 200').bind(id).all()).results});
if(action==='chat'&&r.method==='POST'){const b=await body(r);if(typeof b.text!=='string'||b.text.length>500)return j({error:'Short text required'},400);const cookie='shop_'+id.replaceAll('-','');let sid=(r.headers.get('cookie')||'').match(new RegExp('(?:^|; )'+cookie+'=([a-f0-9-]{36})(?:;|$)'))?.[1];let sess=sid?await e.DB.prepare('SELECT * FROM shop_sessions WHERE id=? AND shop_id=?').bind(sid,id).first():null;if(!sess){sid=crypto.randomUUID();await e.DB.prepare('INSERT INTO shop_sessions(id,shop_id,created_at) VALUES(?,?,?)').bind(sid,id,Date.now()).run();sess={created_at:Date.now(),requests:0}}if(sess.requests>=60||Date.now()-sess.created_at>86400000)return j({error:'Session limit reached. Return later.'},429);await e.DB.prepare('UPDATE shop_sessions SET requests=requests+1 WHERE id=? AND shop_id=?').bind(sid,id).run();const out=j({reply:await chat(b.text,sid,id,e.DB)});out.headers.set('set-cookie',`${cookie}=${sid}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=86400`);return out}
if(!await allowed(r,e,id))return j({error:'Wrong shop password or too many attempts'},401);
if(action==='state'&&r.method==='GET')return j({business:s,stock:(await e.DB.prepare('SELECT sku,name,qty,price FROM shop_stock WHERE shop_id=? ORDER BY name').bind(id).all()).results,orders:(await e.DB.prepare('SELECT id,sku,qty,pickup,status,created_at FROM shop_orders WHERE shop_id=? ORDER BY created_at DESC LIMIT 100').bind(id).all()).results});
if(action==='setup'&&r.method==='POST'){const d=details(await body(r));await e.DB.prepare('UPDATE shops SET name=?,hours=?,contact=?,details=? WHERE id=?').bind(...d,id).run();return j({saved:true})}
if(action==='stock'&&r.method==='POST'){const x=item(await body(r));await e.DB.prepare('INSERT INTO shop_stock(shop_id,sku,name,qty,price) VALUES(?,?,?,?,?) ON CONFLICT(shop_id,sku) DO UPDATE SET name=excluded.name,qty=excluded.qty,price=excluded.price,updated_at=CURRENT_TIMESTAMP').bind(id,...x).run();return j({saved:true})}
return j({error:'Not found'},404);
}catch(err){return j({error:err.message==='Store name required'||err.message==='Invalid stock row'?err.message:'Request failed. Check fields and retry.'},400)}}
