
import {j,body,allowed,details} from './multi.mjs';
export function profile(b){if(!['clinic','doctor','salon','service'].includes(b.business_type))throw Error('Invalid business type');const days=String(b.working_days||'').split(',').map(x=>x.trim());if(!days.length||days.some(x=>!['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].includes(x)))throw Error('Choose working days');return [b.business_type,days.join(','),String(b.address||'').slice(0,500),String(b.services||'').slice(0,3000),String(b.fees||'').slice(0,500),'Asia/Kolkata']}
export function slot(b,p){if(!/^\d{4}-\d\d-\d\dT\d\d:\d\d$/.test(b.start)||!/^\d{4}-\d\d-\d\dT\d\d:\d\d$/.test(b.end))throw Error('Use date and time');const start=new Date(b.start+'+05:30'),end=new Date(b.end+'+05:30');if(!Number.isFinite(+start)||!Number.isFinite(+end)||+start<=Date.now()||+end<=+start||+end-+start>86400000)throw Error('Choose a future slot with end after start');const day=new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Kolkata',weekday:'short'}).format(start);if(!p.working_days.split(',').includes(day))throw Error('Slot must be on a working day');if(!String(b.service||'').trim())throw Error('Service required');return [crypto.randomUUID(),start.toISOString(),end.toISOString(),String(b.service).slice(0,150)]}
export async function topUp(e,id,p,now=Date.now()){const iso=new Date(now).toISOString();const c=await e.DB.prepare("SELECT COUNT(*) n FROM appointment_slots WHERE shop_id=? AND status='available' AND starts_at>?").bind(id,iso).first();if(c.n>=20)return 0;const days=p.working_days.split(','),svc=String(p.services||'Demo consultation').split(/[;,]/)[0].trim().slice(0,150)||'Demo consultation';let added=0;for(let d=1;d<=21;d++){const day=new Date(now+d*86400000+19800000).toISOString().slice(0,10);if(!days.includes(new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Kolkata',weekday:'short'}).format(new Date(day+'T12:00:00+05:30'))))continue;for(const [a,b] of [['11:00','12:00'],['15:00','16:00']]){try{await e.DB.prepare('INSERT INTO appointment_slots(id,shop_id,starts_at,ends_at,service) VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),id,new Date(day+'T'+a+':00+05:30').toISOString(),new Date(day+'T'+b+':00+05:30').toISOString(),svc).run();added++}catch{}}}return added}
export async function service(r,e){const u=new URL(r.url),m=u.pathname.match(/^\/api\/shops\/([a-f0-9-]{36})\/(customer|chat|state|setup|slots|book|schedule)$/);if(!m)return null;const [,id,action]=m,p=await e.DB.prepare('SELECT * FROM service_profiles WHERE shop_id=?').bind(id).first();if(!p)return null;try{if(r.method!=='GET'&&r.headers.get('origin')!==u.origin)return j({error:'Origin denied'},403);if(r.method==='POST'&&['chat','book'].includes(action)){const key='service:'+id+':'+(r.headers.get('cf-connecting-ip')||'local')+':'+Math.floor(Date.now()/86400000);const n=await e.DB.prepare('SELECT attempts FROM auth_limits WHERE key=?').bind(key).first();if(n?.attempts>=100)return j({error:'Daily limit reached'},429);await e.DB.prepare('INSERT INTO auth_limits(key,attempts) VALUES(?,1) ON CONFLICT(key) DO UPDATE SET attempts=attempts+1').bind(key).run();}const s=await e.DB.prepare('SELECT name,hours,contact,details,is_demo FROM shops WHERE id=?').bind(id).first();const slots=async()=>(await e.DB.prepare("SELECT id,starts_at,ends_at,service FROM appointment_slots WHERE shop_id=? AND status='available' AND starts_at>? ORDER BY starts_at LIMIT 100").bind(id,new Date().toISOString()).all()).results.filter(x=>p.working_days.split(',').includes(new Intl.DateTimeFormat('en-US',{timeZone:p.timezone,weekday:'short'}).format(new Date(x.starts_at))));const pub={...s,...p};delete pub.shop_id;
if(action==='customer'&&r.method==='GET'){if(s.is_demo)await topUp(e,id,p);return j({business:pub,slots:await slots()})}
if(action==='chat'&&r.method==='POST'){const b=await body(r);if(typeof b.text!=='string'||b.text.length>500)return j({error:'Short text required'},400);const t=b.text.toLowerCase();let reply;if(/stock|pickup/.test(t))reply='This business uses appointments, not stock/pickup. Choose an available slot below.';else if(/sat|sun|day|hour|tim|available/.test(t))reply=`Working days: ${p.working_days}. Hours: ${s.hours||'Ask owner'}. Closed on days not listed. All appointment times: ${p.timezone}. Choose a published slot below.`;else if(/phone|contact|number/.test(t))reply=s.contact||'Contact not configured.';else if(/address|where|location/.test(t))reply=p.address||'Address not configured.';else if(/fee|price|cost/.test(t))reply=p.fees||'Ask owner for fees.';else if(/service/.test(t))reply=p.services||'Ask owner for services.';else reply=`Welcome to ${s.name}. Ask working days, hours, fees, services, address or contact. Choose a slot below to book. No payment here. Do not send medical details.`;return j({reply})}
if(action==='book'&&r.method==='POST'){const b=await body(r);if(b.confirm!==true||typeof b.name!=='string'||!b.name.trim()||b.name.length>100||typeof b.contact!=='string'||!b.contact.trim()||b.contact.length>150)return j({error:'Review and confirm name/contact and slot'},400);const x=await e.DB.prepare("SELECT * FROM appointment_slots WHERE id=? AND shop_id=? AND status='available' AND starts_at>?").bind(b.slot_id,id,new Date().toISOString()).first();if(!x)return j({error:'Slot no longer available. Refresh and choose another.'},409);if(!p.working_days.split(',').includes(new Intl.DateTimeFormat('en-US',{timeZone:p.timezone,weekday:'short'}).format(new Date(x.starts_at))))return j({error:'Closed on that day. Contact owner.'},409);const bid=crypto.randomUUID();try{await e.DB.prepare('INSERT INTO appointments(id,shop_id,slot_id,customer_name,contact) VALUES(?,?,?,?,?)').bind(bid,id,x.id,b.name.trim(),b.contact.trim()).run()}catch{return j({error:'Slot just booked by someone else. Refresh and choose another.'},409)}return j({booked:true,id:bid,slot:x,note:s.is_demo?'Fictional demo appointment. No real visit.':'Saved in owner dashboard. Contact owner to change or cancel. No payment or outside calendar invitation.'},201)}
if(!await allowed(r,e,id))return j({error:'Wrong shop password or too many attempts'},401);
if(action==='state'&&r.method==='GET')return j({business:pub,slots:(await e.DB.prepare('SELECT * FROM appointment_slots WHERE shop_id=? AND starts_at>? ORDER BY starts_at LIMIT 200').bind(id,new Date().toISOString()).all()).results,appointments:(await e.DB.prepare('SELECT a.id,a.customer_name,a.contact,a.created_at,s.starts_at,s.ends_at,s.service FROM appointments a JOIN appointment_slots s ON s.id=a.slot_id AND s.shop_id=a.shop_id WHERE a.shop_id=? AND s.starts_at>? ORDER BY s.starts_at LIMIT 200').bind(id,new Date().toISOString()).all()).results});
if(action==='slots'&&r.method==='POST'){const b=await body(r),x=slot(b,p);await e.DB.prepare('INSERT INTO appointment_slots(id,shop_id,starts_at,ends_at,service) VALUES(?,?,?,?,?)').bind(x[0],id,...x.slice(1)).run();return j({saved:true})}
if(action==='schedule'&&r.method==='POST'){const b=await body(r),d=details(b),v=profile({...b,business_type:p.business_type});await e.DB.batch([e.DB.prepare('UPDATE shops SET name=?,hours=?,contact=?,details=? WHERE id=?').bind(...d,id),e.DB.prepare('UPDATE service_profiles SET business_type=?,working_days=?,address=?,services=?,fees=?,timezone=? WHERE shop_id=?').bind(...v,id)]);return j({saved:true})}
return j({error:'Not available for appointment businesses'},404);
}catch(err){return j({error:['Use date and time','Service required','Choose working days','Slot must be on a working day','Choose a future slot with end after start','Store name required'].includes(err.message)?err.message:'Could not save. Check fields; duplicate start times are not allowed.'},400)}}
