import {service} from './service.mjs';
import {multi} from './multi.mjs';

import {classify,stockReply,validSignature} from './core.mjs';
const json=(x,status=200)=>new Response(JSON.stringify(x),{status,headers:{'content-type':'application/json','cache-control':'no-store'}});
const parse=async r=>{if(Number(r.headers.get('content-length')||0)>30000)throw Error('too_large');const text=await r.text();if(text.length>30000)throw Error('too_large');return JSON.parse(text);};
function authorized(r,e){return !!e.ADMIN_TOKEN&&r.headers.get('authorization')===`Bearer ${e.ADMIN_TOKEN}`;}
async function reply(text,customer,env){if(env.LIVE_SEND!=='true')return {dryRun:true};if(!env.WA_TOKEN||!env.PHONE_NUMBER_ID)throw Error('send_not_configured');const r=await fetch(`https://graph.facebook.com/${env.GRAPH_VERSION}/${env.PHONE_NUMBER_ID}/messages`,{method:'POST',headers:{authorization:`Bearer ${env.WA_TOKEN}`,'content-type':'application/json'},body:JSON.stringify({messaging_product:'whatsapp',to:customer,type:'text',text:{body:text.slice(0,4000)}})});if(!r.ok)throw Error('send_failed');return r.json();}
async function handle(text,customer,env){const db=env.DB;const s=await db.prepare('SELECT * FROM settings WHERE id=1').first();if(!s)return 'Store setup is not complete. Please contact the owner.';const c=classify(text);
 if(c.kind==='greeting')return `Hi! Welcome to ${s.name}. How may I help you? Send /stock, ask hours or owner contact. Pickup: /order item-code | quantity | pickup time. This bot does not collect payments.`;
 if(c.kind==='contact')return s.contact||'Public contact not provided by owner.';
 if(c.kind==='hours')return s.hours||'Opening hours not provided by owner.';
 if(text.trim().toLowerCase()==='/stock'){const rows=(await db.prepare('SELECT * FROM stock ORDER BY name LIMIT 40').all()).results;return rows.length?rows.map(x=>`${x.sku}: ${x.name} - ${x.qty} available${x.price?' - '+x.price:''}`).join('\n')+'\nAvailability is based on store-maintained stock.':'No stock has been added.';}
 if(c.kind==='stock'){const rows=(await db.prepare('SELECT * FROM stock LIMIT 200').all()).results;const matches=rows.filter(x=>c.text.includes(x.sku.toLowerCase())||c.text.includes(x.name.toLowerCase()));return stockReply(matches.length===1?matches[0]:null);}
 if(c.kind==='order'){if(c.qty<1||c.qty>100||c.pickup.length>120)return 'Please use quantity 1-100 and a short pickup time.';const item=await db.prepare('SELECT * FROM stock WHERE sku=?').bind(c.sku).first();if(!item||item.qty<c.qty)return 'That item/quantity is not currently available. Send /stock for the current list.';const id=crypto.randomUUID();await db.prepare('INSERT INTO pending VALUES(?,?,?,?,?,?)').bind(id,customer,c.sku,c.qty,c.pickup,Date.now()).run();return `Review pickup request: ${c.qty} x ${item.name}; pickup ${c.pickup}; ${item.price||'price to be confirmed by store'}. No payment or reservation yet. Confirm within 15 minutes: /confirm ${id}. Final stock is rechecked then. For cancellations, contact ${s.contact||'the owner'}.`;}
 if(c.kind==='confirm'){const existing=await db.prepare('SELECT * FROM orders WHERE id=? AND customer=?').bind(c.id,customer).first();if(existing)return `Order ${c.id} already saved. No duplicate order created.`;const p=await db.prepare('SELECT * FROM pending WHERE id=? AND customer=?').bind(c.id,customer).first();if(!p||Date.now()-p.created_at>900000)return 'Request expired or not found. Start a new /order.';try{await db.batch([db.prepare('INSERT INTO orders(id,customer,sku,qty,pickup) SELECT id,customer,sku,qty,pickup FROM pending WHERE id=? AND customer=?').bind(c.id,customer),db.prepare('DELETE FROM pending WHERE id=?').bind(c.id)]);}catch{return 'Could not save the order. Stock may have changed. Please check /stock or contact the owner.';}return `Order saved: ${c.id}. ${p.qty} x ${p.sku}, pickup ${p.pickup}. Reserved from store stock. The order is visible in the owner dashboard. No WhatsApp alert or payment was sent. Contact the owner for changes.`;}
 return `Ask /stock, hours, or owner contact. To request pickup: /order item-code | quantity | pickup time. ${s.details.slice(0,1200)}`;
}
export default {async fetch(r,e){const u=new URL(r.url);try{const services=await service(r,e);if(services)return services;const scoped=await multi(r,e);if(scoped)return scoped;
 if(u.pathname==='/api/customer'&&r.method==='GET'){const b=await e.DB.prepare('SELECT name,hours,contact,details FROM settings WHERE id=1').first();return json({business:b,stock:(await e.DB.prepare('SELECT sku,name,qty,price,updated_at FROM stock ORDER BY name LIMIT 40').all()).results});}
 if(u.pathname==='/api/web-chat'&&r.method==='POST'){if(r.headers.get('origin')!==u.origin)return json({error:'Origin denied'},403);const b=await parse(r);if(typeof b.text!=='string'||b.text.length>500)return json({error:'Short text required'},400);const existing=(r.headers.get('cookie')||'').match(/(?:^|; )shop_chat=([a-f0-9-]{36})(?:;|$)/);let id=existing?.[1];let session=id?await e.DB.prepare('SELECT * FROM web_sessions WHERE id=?').bind(id).first():null;if(!session){id=crypto.randomUUID();await e.DB.prepare('INSERT INTO web_sessions(id,created_at) VALUES(?,?)').bind(id,Date.now()).run();session={created_at:Date.now(),requests:0};}if(session.requests>=60||Date.now()-session.created_at>86400000)return json({error:'Demo session limit reached. Please return later.'},429);await e.DB.prepare('UPDATE web_sessions SET requests=requests+1 WHERE id=?').bind(id).run();const text=await handle(b.text,'web:'+id,e);return new Response(JSON.stringify({reply:text}),{headers:{'content-type':'application/json','cache-control':'no-store','set-cookie':`shop_chat=${id}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=86400`}});}
 if(u.pathname==='/webhook'&&r.method==='GET'){const v=u.searchParams;if(e.VERIFY_TOKEN&&v.get('hub.mode')==='subscribe'&&v.get('hub.verify_token')===e.VERIFY_TOKEN)return new Response(v.get('hub.challenge'));return new Response('Denied',{status:403});}
 if(u.pathname==='/webhook'&&r.method==='POST'){const body=await r.text();if(body.length>1000000)return new Response('Too large',{status:413});if(!await validSignature(body,r.headers.get('x-hub-signature-256'),e.META_APP_SECRET))return new Response('Denied',{status:403});const payload=JSON.parse(body);for(const entry of payload.entry||[])for(const change of entry.changes||[]){const v=change.value;if(v?.metadata?.phone_number_id!==e.PHONE_NUMBER_ID)continue;for(const m of v.messages||[]){if(m.type!=='text'||!m.id||!/^\d{5,20}$/.test(m.from)||!m.timestamp||Date.now()/1000-Number(m.timestamp)>86400)continue;const claim=await e.DB.prepare("INSERT OR IGNORE INTO events(id,status) VALUES(?,'processing')").bind(m.id).run();if(!claim.meta.changes)continue;try{const text=await handle((m.text?.body||'').slice(0,2000),m.from,e);await reply(text,m.from,e);await e.DB.prepare("UPDATE events SET status=? WHERE id=?").bind(e.LIVE_SEND==='true'?'sent':'dry-run',m.id).run();}catch{await e.DB.prepare("UPDATE events SET status='needs-review' WHERE id=?").bind(m.id).run();}}}return new Response('OK');}
 if(u.pathname.startsWith('/api/')){if(!authorized(r,e))return json({error:'Unauthorized'},401);if(u.pathname==='/api/state'&&r.method==='GET')return json({business:await e.DB.prepare('SELECT * FROM settings WHERE id=1').first(),stock:(await e.DB.prepare('SELECT * FROM stock ORDER BY name').all()).results,orders:(await e.DB.prepare('SELECT * FROM orders ORDER BY created_at DESC LIMIT 100').all()).results,events:(await e.DB.prepare("SELECT * FROM events WHERE status='needs-review' LIMIT 50").all()).results,dryRun:e.LIVE_SEND!=='true'});
 if(u.pathname==='/api/setup'&&r.method==='POST'){const b=await parse(r);if(!b.name||String(b.name).length>150)return json({error:'Name required'},400);await e.DB.prepare('INSERT INTO settings VALUES(1,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,hours=excluded.hours,contact=excluded.contact,details=excluded.details').bind(String(b.name),String(b.hours||'').slice(0,300),String(b.contact||'').slice(0,500),String(b.details||'').slice(0,6000)).run();return json({saved:true});}
 if(u.pathname==='/api/stock'&&r.method==='POST'){const b=await parse(r);if(!/^[a-z0-9-]{1,40}$/.test(b.sku)||!b.name||!Number.isInteger(b.qty)||b.qty<0||b.qty>100000)return json({error:'Invalid stock'},400);await e.DB.prepare('INSERT INTO stock(sku,name,qty,price) VALUES(?,?,?,?) ON CONFLICT(sku) DO UPDATE SET name=excluded.name,qty=excluded.qty,price=excluded.price,updated_at=CURRENT_TIMESTAMP').bind(b.sku,String(b.name).slice(0,100),b.qty,String(b.price||'').slice(0,100)).run();return json({saved:true});}
 return json({error:'Not found'},404);}
 return e.ASSETS.fetch(r);
 }catch{return json({error:'Request failed; check configuration and dashboard event status.'},500);}}};
